version: '3.9'

services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_ROOT_USER: '${MYSQL_USER}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - 'sailmysql:/var/lib/mysql'

volumes:
  sailmysql:
    driver: local
